template:
  name: ""
  repository: ""
  version: ""
  commit: null

project:
  name: "dijon"
  package: "dijon"
  cli: "dijon"
  created_at: "UNKNOWN"
  copier_answers_file: ".copier-answers.yml"

updates:
  last_applied:
    version: null
    commit: null
    applied_at: "2026-01-13"
  history:

  - version: null
    commit: null
    applied_at: "2026-01-13"
